:d = http://localhost:8081

# get all user
GET :d/user/1/2

# login wrong
POST :d/login
content-type: application/json
{
  "username": "nhatk",
  "password": "123456"
}

# get all user
POST :d/register
content-type: application/json
{
  "username": "nhat",
  "password": "123456"
}

# get single
GET :d/test-post

# patch
PATCH :d/hello
content-type: application/json
user-agent: emacs resclient
{
  "name": "Nhat"
}

#kfas
GET :d/ab

# post product
POST :d/ab
content-type: application/json
user-agent: emacs resclient
{
  "namke": "sdjka"
}

# post product
POST :d/req
content-type: application/json
user-agent: emacs resclient
{
  "name": "sdja"
}

# post product
POST :d/aa
content-type: application/json
user-agent: emacs resclient
{
  "name": "sdja"
}

# post product
POST :d/test-post
content-type: application/json
user-agent: emacs resclient
{
  "name": "product 3"
}

# update product
PUT :d/products/1
{
  "title": "product 1 renamesfdd",
  "price": "wtf"
}

# https://www.reddit.com/r/Clojure/comments/mxx6eh/back_to_ring_compojure_still_having_a_problem/
